# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'Accessing Slate'
      link: '/usage/accessing-slate'
    - label: 'Dashboard'
      link: '/usage/dashboard'
    - label: 'Category'
      link: '/usage/category'
    - label: 'Create an order'
      link: '/usage/create-an-order'
    - label: 'Inventory'
      link: '/usage/inventory'
    - label: 'Locations'
      link: '/usage/locations'
    - label: 'Taxes'
      link: '/usage/taxes'
    - label: 'Discounts'
      link: '/usage/discounts'
    - label: 'Customers'
      link: '/usage/customers'  
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/jpedroschmitz/rocketdocs
